### ISSUE TITLE
Not able to register the device

### ISSUE THREAD

**Issue by raviRocks** [mautini/google-assistant-java-demo#8]
Hi,
I am not able to register the device, PFB logs:
Exception in thread "main" com.mautini.assistant.demo.exception.DeviceRegisterException: Unable to register the device model
	at com.mautini.assistant.demo.device.DeviceRegister.lambda$1(DeviceRegister.java:65)
	at java.util.Optional.orElseThrow(Unknown Source)
	at com.mautini.assistant.demo.device.DeviceRegister.register(DeviceRegister.java:65)
	at com.mautini.assistant.demo.GoogleAssistantClient.main(GoogleAssistantClient.java:53)

I followed the steps mentioned in readme.
Could you please support me?

**Comment by mautini** [comment]
Hello,

I haven't updated the library for a long time, maybe the Google API changed... I don't really have time to check now but I will let you know if I fix it in the future...

**Comment by mautini** [comment]
I just did a lot of fixes to the lib and it works in my computer now. If you are still interested (3 years latter :D), you should try
